### ISSUE TITLE
Chess game

### ISSUE THREAD

**Issue by Alcalol** [FrenchYann/Chess3D#1]
Hi, I couldn't figure out a way of contacting you besides from raising a new issue... I hope you don't mind.  The Chess3D game you've currently posted is against AI only, would you be able to give me some hints as to what I would need to modify to create a 2 player version? (Or perhaps both?)

Thanks

ps.  Great job on the game, it looks very nice and works well too!

**Comment by FrenchYann** [comment]
Raising an issue seems like a good way to me (:

Humm it seems it works if in the chess.js file in line 279 you replace:

```
setTimeout(SearchAndRedraw, 0);
```

by:

```
g_playerWhite = !g_playerWhite;
```

Though if you were talking about remote 2 players, you might need to do a bit more (server + AJAX)

**Comment by Alcalol** [comment]
Cool, thanks!  It's exactly what I was looking for.  I also set a global variable called useAI to toggle AI on and off and place the above two lines in an if statement.

Also for the benefit for anyone else who may be interested, I added the following to the function newGameDialog in gui.js just before the line "$newGame.dialog...." to allow users to choose whether they want to play against AI or a friend using the boolean declared above.

```
            //Default mode is against friend so hide unnecessary controls from user
    $radio.hide();
    $label.hide();
    $levelSelect.hide();

            //initialize boolean for AI setting
    useAI = false;

            //Add a checkbox which toggles AI mode and hides buttons that are not necessary
    var $aiCheckbox = $("<input type='checkbox'>Play against computer</input>").change(function() {
                                                if (this.checked){
                                                                                                         //Enable AI and show controls
                                                     $radio.show();
                                                     $label.show();
                                                     $levelSelect.show();
                                                     useAI = true;
                                                }
                                                else{
                                                                                                         //Disable AI and hide controls
                                                     $radio.hide();
                                                     $label.hide();
                                                     $levelSelect.hide();
                                                     useAI = false;
                                                }
                                            }).appendTo($newGame);
```

Once again thanks for your help :)
